var annotated_dup =
[
    [ "BOOTINFO", "struct_b_o_o_t_i_n_f_o.html", "struct_b_o_o_t_i_n_f_o" ],
    [ "CONSOLE", "struct_c_o_n_s_o_l_e.html", "struct_c_o_n_s_o_l_e" ],
    [ "DLL_STRPICENV", "struct_d_l_l___s_t_r_p_i_c_e_n_v.html", "struct_d_l_l___s_t_r_p_i_c_e_n_v" ],
    [ "FIFO32", "struct_f_i_f_o32.html", "struct_f_i_f_o32" ],
    [ "FILEHANDLE", "struct_f_i_l_e_h_a_n_d_l_e.html", "struct_f_i_l_e_h_a_n_d_l_e" ],
    [ "FILEINFO", "struct_f_i_l_e_i_n_f_o.html", "struct_f_i_l_e_i_n_f_o" ],
    [ "FREEINFO", "struct_f_r_e_e_i_n_f_o.html", "struct_f_r_e_e_i_n_f_o" ],
    [ "GATE_DESCRIPTOR", "struct_g_a_t_e___d_e_s_c_r_i_p_t_o_r.html", "struct_g_a_t_e___d_e_s_c_r_i_p_t_o_r" ],
    [ "HUFF", "struct_h_u_f_f.html", "struct_h_u_f_f" ],
    [ "JPEG", "struct_j_p_e_g.html", "struct_j_p_e_g" ],
    [ "MEMMAN", "struct_m_e_m_m_a_n.html", "struct_m_e_m_m_a_n" ],
    [ "MOUSE_DEC", "struct_m_o_u_s_e___d_e_c.html", "struct_m_o_u_s_e___d_e_c" ],
    [ "RGB", "struct_r_g_b.html", "struct_r_g_b" ],
    [ "SEGMENT_DESCRIPTOR", "struct_s_e_g_m_e_n_t___d_e_s_c_r_i_p_t_o_r.html", "struct_s_e_g_m_e_n_t___d_e_s_c_r_i_p_t_o_r" ],
    [ "SHEET", "struct_s_h_e_e_t.html", "struct_s_h_e_e_t" ],
    [ "SHTCTL", "struct_s_h_t_c_t_l.html", "struct_s_h_t_c_t_l" ],
    [ "TASK", "struct_t_a_s_k.html", "struct_t_a_s_k" ],
    [ "TASKCTL", "struct_t_a_s_k_c_t_l.html", "struct_t_a_s_k_c_t_l" ],
    [ "TASKLEVEL", "struct_t_a_s_k_l_e_v_e_l.html", "struct_t_a_s_k_l_e_v_e_l" ],
    [ "tek_STR_BITMODEL", "structtek___s_t_r___b_i_t_m_o_d_e_l.html", "structtek___s_t_r___b_i_t_m_o_d_e_l" ],
    [ "tek_STR_PRB", "structtek___s_t_r___p_r_b.html", "structtek___s_t_r___p_r_b" ],
    [ "tek_STR_RNGDEC", "structtek___s_t_r___r_n_g_d_e_c.html", "structtek___s_t_r___r_n_g_d_e_c" ],
    [ "TIMER", "struct_t_i_m_e_r.html", "struct_t_i_m_e_r" ],
    [ "TIMERCTL", "struct_t_i_m_e_r_c_t_l.html", "struct_t_i_m_e_r_c_t_l" ],
    [ "TSS32", "struct_t_s_s32.html", "struct_t_s_s32" ]
];